export const REGION_OPTIONS = [
  { value: 0, label: "서울" },
  { value: 1, label: "경기" },
  { value: 2, label: "인천" },
  { value: 3, label: "강원" },
  { value: 4, label: "제주" },
  { value: 5, label: "대전" },
  { value: 6, label: "충북" },
  { value: 7, label: "충남" },
  { value: 8, label: "세종" },
  { value: 9, label: "부산" },
  { value: 10, label: "울산" },
  { value: 11, label: "경남" },
  { value: 12, label: "대구" },
  { value: 13, label: "경북" },
  { value: 14, label: "광주" },
  { value: 15, label: "전남" },
  { value: 16, label: "전주" },
  { value: 17, label: "전북" },
];
